// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUN0Z19FDXg7zhwOUzS2ThutgewjsYVM',
    appId: '1:986587303709:web:2dfbf13005b28b586f5bf4',
    messagingSenderId: '986587303709',
    projectId: 'frontend-97e53',
    authDomain: 'frontend-97e53.firebaseapp.com',
    storageBucket: 'frontend-97e53.firebasestorage.app',
    measurementId: 'G-JGGPMS3EXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxFepyR9JW543GFRgttECa40LAfph_wc',
    appId: '1:986587303709:android:c2b4f18c154b3e0e6f5bf4',
    messagingSenderId: '986587303709',
    projectId: 'frontend-97e53',
    storageBucket: 'frontend-97e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknnUSOsaK7W_gLeqfZitmdESWuq088dA',
    appId: '1:986587303709:ios:e0ebb21f093289246f5bf4',
    messagingSenderId: '986587303709',
    projectId: 'frontend-97e53',
    storageBucket: 'frontend-97e53.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknnUSOsaK7W_gLeqfZitmdESWuq088dA',
    appId: '1:986587303709:ios:e0ebb21f093289246f5bf4',
    messagingSenderId: '986587303709',
    projectId: 'frontend-97e53',
    storageBucket: 'frontend-97e53.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDUN0Z19FDXg7zhwOUzS2ThutgewjsYVM',
    appId: '1:986587303709:web:d08c926667b400376f5bf4',
    messagingSenderId: '986587303709',
    projectId: 'frontend-97e53',
    authDomain: 'frontend-97e53.firebaseapp.com',
    storageBucket: 'frontend-97e53.firebasestorage.app',
    measurementId: 'G-ZBJ3XCHDC8',
  );
}
